# Generated by Django 5.2.4 on 2025-07-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_remove_assessment_results_assessmentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='standard',
            field=models.CharField(default='OWASP', max_length=50),
            preserve_default=False,
        ),
    ]
